### PR TITLE
Fixed Upvoot error and UI Improvements

### PR DESCRIPTION
**Pull request by omkarnagarkar55**
Done following changes changes :- 

1. UI Improvements
2. Fix Upvote Error Issue When Not Logged In
3. Change saving location for Images
4. Add new logo.
5. Remove Comment.

Please review and approve.

Thanks,
Omkar.

### CODE REVIEW

**Comment by sangramjagtap2108** [comment]
Looks good to me

**Review by sangramjagtap2108 — COMMENTED** [review]
Changes look good

**Comment by omkarnagarkar55** [comment]
Reopening PR which was closed by mistake.

**Comment by omkarnagarkar55** [comment]
Reopening PR which was closed by mistake.

**Review by sangramjagtap2108 — APPROVED** [review]
Looks good to me, merging the PR

**Pull request merged**
